package com.example.t.application.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.t.app.entity.MyGrid_Item;

import com.example.t.application.dao.MyGrid_ItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myGrid_ItemDaoConfig;

    private final MyGrid_ItemDao myGrid_ItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myGrid_ItemDaoConfig = daoConfigMap.get(MyGrid_ItemDao.class).clone();
        myGrid_ItemDaoConfig.initIdentityScope(type);

        myGrid_ItemDao = new MyGrid_ItemDao(myGrid_ItemDaoConfig, this);

        registerDao(MyGrid_Item.class, myGrid_ItemDao);
    }
    
    public void clear() {
        myGrid_ItemDaoConfig.clearIdentityScope();
    }

    public MyGrid_ItemDao getMyGrid_ItemDao() {
        return myGrid_ItemDao;
    }

}
